name: Build Kernel A235F KSU-Next
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Environment & Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev clang lld gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi make git python2
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Manual Inject KernelSU-Next
      run: |
        # bersihkan sisa-sisa lama
        rm -rf KernelSU-Next drivers/kernelsu
        
        # clone repo ksu-next
        git clone --depth 1 https://github.com/KernelSU-Next/KernelSU-Next
        
        # pindahkan isinya & HAPUS folder .git biar gak dianggap submodule
        cp -r KernelSU-Next/kernel drivers/kernelsu
        rm -rf KernelSU-Next
        rm -rf drivers/kernelsu/.git
        
        # inject ke Kconfig & Makefile
        sed -i '/kernelsu/d' drivers/Kconfig
        sed -i '/kernelsu/d' drivers/Makefile
        sed -i '2i source "drivers/kernelsu/Kconfig"' drivers/Kconfig
        echo "obj-y += kernelsu/" >> drivers/Makefile
        echo "[+] manual injection ksu-next success"

    - name: Build Kernel (Samsung A235F)
      run: |
        export ARCH=arm64
        mkdir -p out/arch/arm64/boot/dts
        make -C $(pwd) O=$(pwd)/out mrproper
        
        # ambil config asli
        make -C $(pwd) O=$(pwd)/out DTC_EXT=$(pwd)/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y CLANG_TRIPLE=aarch64-linux-gnu- a23_eur_open_defconfig
        
        # otomatis isi menu baru
        make -C $(pwd) O=$(pwd)/out DTC_EXT=$(pwd)/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y CLANG_TRIPLE=aarch64-linux-gnu- olddefconfig

        # matikan debug info & matikan semua warning agar log bersih
        scripts/config --file out/.config -d DEBUG_INFO -d DEBUG_INFO_DWARF4 -d DEBUG_INFO_DWARF5
        
        # kompilasi utama dengan flag -w (ignore all warnings)
        make -j$(nproc --all) -C $(pwd) O=$(pwd)/out \
             DTC_EXT=$(pwd)/tools/dtc \
             CONFIG_BUILD_ARM64_DT_OVERLAY=y \
             CLANG_TRIPLE=aarch64-linux-gnu- \
             CC=clang \
             CROSS_COMPILE=aarch64-linux-gnu- \
             CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
             KCFLAGS="-w -gdwarf-4"

    - name: Upload Hasil Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-A235F-KSUNext
        path: out/arch/arm64/boot/Image
